// Blanc Manger Coco - Card Deck
// Question cards use ____ as the blank placeholder

const QUESTION_CARDS = [
    "Quand j'étais petit, je rêvais de ____.",
    "Le secret d'un mariage heureux ? ____.",
    "Mon patron m'a surpris en train de ____.",
    "En France, on ne plaisante pas avec ____.",
    "La prochaine invention révolutionnaire : ____.",
    "Le pire cadeau de Noël : ____.",
    "Si j'étais président, j'interdirais ____.",
    "Le meilleur remède contre la gueule de bois : ____.",
    "Ma grand-mère cache ____ sous son lit.",
    "Le nouveau cours obligatoire à l'école : ____.",
    "Ce que les aliens penseraient en visitant la Terre : ____.",
    "Le dernier message WhatsApp de ma mère : ____.",
    "La vraie raison du réchauffement climatique : ____.",
    "Ce qui se passe vraiment dans les vestiaires : ____.",
    "Le prochain scandale politique : ____.",
    "Mon talent caché : ____.",
    "La chose la plus française qui existe : ____.",
    "Ce que fait le prof quand il est seul : ____.",
    "Le vrai sens de la vie : ____.",
    "Pourquoi je suis en retard au travail : ____.",
    "Le secret de la recette de ma grand-mère : ____.",
    "Ce qu'on trouve dans le sac d'un étudiant : ____.",
    "Le meilleur moyen de draguer : ____.",
    "Ce que cache le Père Noël dans sa hotte : ____.",
    "Le sujet tabou au dîner de famille : ____.",
    "Ma résolution du Nouvel An : arrêter ____.",
    "Le sport national français devrait être ____.",
    "Ce qui manque à la tour Eiffel : ____.",
    "Le dernier truc à la mode : ____.",
    "La pire excuse pour sécher les cours : ____.",
    "Au menu de la cantine aujourd'hui : ____.",
    "Ce que je fais quand personne ne regarde : ____.",
    "Le nouveau slogan de la France : ____.",
    "Ce qu'on entend vraiment à confesse : ____.",
    "Le problème avec les jeunes d'aujourd'hui : ____.",
    "La face cachée de Disneyland : ____.",
    "Ce que Google sait sur moi : ____.",
    "Le vrai pouvoir de Chuck Norris : ____.",
    "Pendant l'apocalypse, je prendrai ____ avec moi.",
    "La seule chose qui pourrait sauver 2026 : ____.",
    "Le truc qu'on ne dit jamais en entretien d'embauche : ____.",
    "La huitième merveille du monde : ____.",
    "Ce que murmure le pape quand il est seul : ____.",
    "Le remède miracle contre la calvitie : ____.",
    "Ce qu'on apprend pas à l'école : ____.",
    "La raison pour laquelle les dinosaures ont disparu : ____.",
    "Le vrai ingrédient secret du Coca-Cola : ____.",
    "Ce qui se passe dans l'Area 51 : ____.",
    "Le prochain film Marvel : ____ contre ____.",
    "La devise de ma famille : ____.",
];

const ANSWER_CARDS = [
    "Un fromage qui pue",
    "La grève des transports",
    "Mon ex",
    "Les 35 heures",
    "Un apéro qui dure 3 jours",
    "La bise à un inconnu",
    "Un croissant rassis",
    "Le RSA",
    "Une raclette à 3h du matin",
    "Le droit de cuissage",
    "Un gilet jaune",
    "La Joconde qui sourit vraiment",
    "Un stage non rémunéré",
    "Le camembert nucléaire",
    "Un bébé qui juge",
    "Netflix et procrastination",
    "Le syndrome de la page blanche",
    "Une baguette comme arme",
    "Les impôts sur les impôts",
    "Une sieste existentielle",
    "Le Wi-Fi du voisin",
    "La queue à la Poste",
    "Un cours de philo à 8h",
    "La Sécu en faillite",
    "Un selfie avec le pape",
    "Les toilettes turques",
    "Un débat sur la chocolatine",
    "Le Père Noël au chômage",
    "Un karaoké de Johnny",
    "La triche au bac",
    "Les soldes chez Ikea",
    "Un match de pétanque truqué",
    "La fin du monde",
    "Un régime qui commence lundi",
    "Les pigeons de Paris",
    "Un pot de départ interminable",
    "Le permis de conduire à points",
    "Une manif qui tourne mal",
    "Le Tour de France dopé",
    "Un week-end chez belle-maman",
    "La file d'attente à Pôle Emploi",
    "Un mojito tiède",
    "Le syndrome de Stockholm",
    "Un PowerPoint de 200 slides",
    "La retraite à 95 ans",
    "Les moustiques en été",
    "Un tatouage raté",
    "Le lundi matin",
    "Un escape game avec sa famille",
    "La 5G dans le cerveau",
    "Un Jean-Pierre Foucault immortel",
    "Le complot des Illuminati",
    "Les Playmobil révolutionnaires",
    "Un barbecue végan",
    "Le code de la route",
    "Une lettre de motivation sincère",
    "Le mystère de la chaussette perdue",
    "Un enterrement de vie de garçon",
    "La météo de Brest",
    "Un steak haché surgelé",
    "Les abdos de Macron",
    "Le fantôme de De Gaulle",
    "Un match nul 0-0",
    "La flemme cosmique",
    "Un chat qui domine le monde",
    "Le sens de la vie (spoiler : 42)",
    "Une connexion Internet Explorer",
    "Un TGV en retard",
    "La calvitie précoce",
    "Un voyage scolaire en enfer",
    "Les soldes chez Lidl",
    "Le Nutella en rupture de stock",
    "Les Gaulois réfractaires",
    "Un algorithme de Tinder",
    "La crise de la quarantaine",
    "Un croissant au beurre de cacahuète",
    "La machine à café en panne",
    "Un week-end pluvieux en Normandie",
    "Le parking de Carrefour un samedi",
    "Une conspiration de chats",
    "Les cours de natation du président",
    "Un SMS envoyé à la mauvaise personne",
    "La police des mèmes",
    "Un dîner chez les Tuche",
    "L'odeur du métro en été",
    "Un robot qui fait la grève",
    "Le monde sans pain au chocolat",
    "Une réunion qui aurait pu être un email",
    "Un Kinder Surprise pour adultes",
    "Le retour des cassettes VHS",
    "Un brunch à 45 euros",
    "La philosophie de Jean-Claude Van Damme",
    "Un podcast sur la fiscalité",
    "Le comité des fêtes en colère",
    "Un influenceur à la retraite",
    "La privatisation de l'air",
    "Un escape game dans l'administration française",
    "Le dernier iPhone à 3000 euros",
    "Une garde à vue chez Mamie",
    "Le club des tricoteurs anonymes",
    "Un coach de vie en dépression",
    "La théorie du complot du gruyère",
    "Les ronds-points de province",
    "Un millionnaire au SMIC",
    "Le savoir-vivre à la française",
    "Une pizza hawaïenne devant un Italien",
    "Le recyclage des excuses",
    "Un chien influenceur",
    "La mondialisation du saucisson",
    "Un cours de yoga agressif",
    "La diplomatie du barbecue",
    "Un pot de Nutella vide",
    "Le 49.3 des sentiments",
    "Les pigeons espions du gouvernement",
    "Un apéro Teams",
    "La crise de nerfs au Monopoly",
    "Un road trip en Twingo",
    "Le droit à la paresse",
    "Une invasion de beaux-parents",
    "Le karma instantané",
    "Un festival de musique sous la pluie",
    "La révolution des post-it",
    "Un match de foot entre philosophes",
    "Le bonheur en CDD",
    "Une cure thermale à Tchernobyl",
    "Le complot des boulangeries",
    "Un stage de méditation avec Gérard Depardieu",
];
