// Owt Manger Coco - Card Deck
// Question cards use ____ as the blank placeholder

const QUESTION_CARDS = [
    // --- Original ---
    "Quand j'étais petit, je rêvais de ____.",
    "Le secret d'un mariage heureux ? ____.",
    "Mon patron m'a surpris en train de ____.",
    "En France, on ne plaisante pas avec ____.",
    "La prochaine invention révolutionnaire : ____.",
    "Le pire cadeau de Noël : ____.",
    "Si j'étais président, j'interdirais ____.",
    "Le meilleur remède contre la gueule de bois : ____.",
    "Ma grand-mère cache ____ sous son lit.",
    "Le nouveau cours obligatoire à l'école : ____.",
    "Ce que les aliens penseraient en visitant la Terre : ____.",
    "Le dernier message WhatsApp de ma mère : ____.",
    "La vraie raison du réchauffement climatique : ____.",
    "Ce qui se passe vraiment dans les vestiaires : ____.",
    "Le prochain scandale politique : ____.",
    "Mon talent caché : ____.",
    "La chose la plus française qui existe : ____.",
    "Ce que fait le prof quand il est seul : ____.",
    "Le vrai sens de la vie : ____.",
    "Pourquoi je suis en retard au travail : ____.",
    "Le secret de la recette de ma grand-mère : ____.",
    "Ce qu'on trouve dans le sac d'un étudiant : ____.",
    "Le meilleur moyen de draguer : ____.",
    "Ce que cache le Père Noël dans sa hotte : ____.",
    "Le sujet tabou au dîner de famille : ____.",
    "Ma résolution du Nouvel An : arrêter ____.",
    "Le sport national français devrait être ____.",
    "Ce qui manque à la tour Eiffel : ____.",
    "Le dernier truc à la mode : ____.",
    "La pire excuse pour sécher les cours : ____.",
    "Au menu de la cantine aujourd'hui : ____.",
    "Ce que je fais quand personne ne regarde : ____.",
    "Le nouveau slogan de la France : ____.",
    "Ce qu'on entend vraiment à confesse : ____.",
    "Le problème avec les jeunes d'aujourd'hui : ____.",
    "La face cachée de Disneyland : ____.",
    "Ce que Google sait sur moi : ____.",
    "Le vrai pouvoir de Chuck Norris : ____.",
    "Pendant l'apocalypse, je prendrai ____ avec moi.",
    "La seule chose qui pourrait sauver 2026 : ____.",
    "Le truc qu'on ne dit jamais en entretien d'embauche : ____.",
    "La huitième merveille du monde : ____.",
    "Ce que murmure le pape quand il est seul : ____.",
    "Le remède miracle contre la calvitie : ____.",
    "Ce qu'on apprend pas à l'école : ____.",
    "La raison pour laquelle les dinosaures ont disparu : ____.",
    "Le vrai ingrédient secret du Coca-Cola : ____.",
    "Ce qui se passe dans l'Area 51 : ____.",
    "Le prochain film Marvel : ____ contre ____.",
    "La devise de ma famille : ____.",

    // --- General (batch 2) ---
    "Le dernier rêve que j'ai fait : ____.",
    "Ce que font les poissons quand on ne regarde pas : ____.",
    "La pire chose à dire à un premier rendez-vous : ____.",
    "Ce que j'ai trouvé dans le frigo de mon coloc : ____.",
    "Le prochain record du monde : ____.",
    "Ce que cache vraiment le Bermuda Triangle : ____.",
    "La raison secrète pour laquelle je suis célibataire : ____.",
    "Le titre de mon autobiographie : ____.",
    "Ce que les profs écrivent vraiment sur les bulletins : ____.",
    "Le pire conseil qu'on m'ait donné : ____.",
    "Ce que fait mon chat quand je pars au travail : ____.",
    "La prochaine loi votée à l'unanimité : ____.",
    "Le secret que tout le monde connaît sauf moi : ____.",
    "Ce qu'on devrait enseigner en maternelle : ____.",
    "La pire chose à crier dans un ascenseur : ____.",
    "Mon dernier achat impulsif : ____.",
    "Ce que je dirais si je rencontrais Dieu : ____.",
    "Le truc que personne n'ose demander au médecin : ____.",
    "La vraie raison pour laquelle les gens font du sport : ____.",
    "Ce que je ferais avec un million d'euros : ____.",
    "Le prochain monument historique classé par l'UNESCO : ____.",
    "Ce qu'on trouve vraiment au bout de l'arc-en-ciel : ____.",
    "Le pire souvenir de colo : ____.",
    "Ce que pense vraiment mon chien de moi : ____.",
    "La chose que tout Français fait en secret : ____.",
    "Le vrai contenu des croissants industriels : ____.",
    "Ce que je ferais si j'étais invisible pendant 24h : ____.",
    "Le prochain sujet du bac philo : ____.",
    "Ce qu'on trouve dans la boîte de Pandore version 2026 : ____.",
    "Le pire tatouage possible : ____.",
    "Ce que raconte vraiment le facteur aux voisins : ____.",
    "La chose la plus overrated au monde : ____.",
    "Ce que je veux qu'on écrive sur ma tombe : ____.",
    "Le truc bizarre que tout le monde fait sous la douche : ____.",
    "Ce que cache le sourire de la Joconde : ____.",
    "Le pire moment pour avoir le hoquet : ____.",
    "Ce qu'il y a vraiment dans les nuggets : ____.",
    "Le prochain phénomène TikTok : ____.",
    "Ce que les bébés pensent vraiment : ____.",
    "La pire idée de team building : ____.",
    "Ce que font les statues la nuit : ____.",
    "Le secret le mieux gardé de la cantine : ____.",
    "La vraie raison pour laquelle on bâille : ____.",
    "Ce qu'il ne faut jamais dire à sa belle-mère : ____.",

    // --- Dev & Tech ---
    "La vraie raison du dernier bug en prod : ____.",
    "Ce qu'on trouve dans le backlog depuis 3 ans : ____.",
    "Le commentaire le plus utile dans le code : // ____.",
    "Ce que le dev fait pendant le daily standup : ____.",
    "La prochaine fonctionnalité demandée par le client : ____.",
    "Pourquoi le déploiement du vendredi a échoué : ____.",
    "Ce que ChatGPT refuse de générer : ____.",
    "Le vrai motif de la mass layoff chez la startup : ____.",
    "Le nom de la prochaine startup licorne : ____.",
    "Ce que fait vraiment le CTO : ____.",
    "La définition de 'done' selon le Product Owner : ____.",
    "Ce qu'on met dans le README mais qui est faux : ____.",
    "Le prochain framework JavaScript : ____.",
    "La raison pour laquelle le build ne passe plus : ____.",
    "Ce que le stagiaire a poussé en prod : ____.",
    "Le vrai contenu du channel #random sur Slack : ____.",
    "Ce que signifie 'on verra en V2' : ____.",
    "Le stack technique idéal selon Twitter : ____.",
    "La dernière excuse pour ne pas écrire de tests : ____.",
    "Ce qu'on dit en rétrospective mais qu'on ne fait jamais : ____.",

    // --- Consulting ---
    "Ce que le consultant facture 1500€/jour : ____.",
    "Le vrai livrable du cabinet de conseil : ____.",
    "Ce qu'on trouve dans la valise du consultant : ____.",
    "La slide la plus importante du deck : ____.",
    "Ce que pense le client quand le consultant parle : ____.",
    "La vraie valeur ajoutée du Big Four : ____.",
    "Le buzzword préféré du partner : ____.",
    "Ce que fait le consultant entre deux missions : ____.",
    "La méthodologie secrète de McKinsey : ____.",
    "Ce qu'on met dans la propale pour gagner : ____.",
    "Le KPI le plus absurde inventé par un consultant : ____.",
    "Ce qui se passe vraiment au séminaire d'intégration : ____.",
    "La vraie raison du turnover en cabinet : ____.",
    "Ce que le manager dit en comité de staffing : ____.",
    "Le template Excel qui a sauvé le projet : ____.",

    // --- General (batch 3) ---
    "Ce que Napoléon ferait en 2026 : ____.",
    "Le contenu du coffre-fort de l'Élysée : ____.",
    "La pire chose à googler au bureau : ____.",
    "Ce que les voisins pensent de moi : ____.",
    "Le prochain sport olympique : ____.",
    "Ce qu'on ne dit pas à un mariage : ____.",
    "La chose qui devrait être illégale : ____.",
    "Le pire nom pour un enfant : ____.",
    "Ce que cache le fond de mon historique de recherche : ____.",
    "La prochaine pandémie sera causée par ____.",
    "Le secret de la longévité : ____.",
    "Ce que murmure l'assistant vocal quand on dort : ____.",
    "Le prochain prix Nobel ira à ____ pour ____.",
    "Ce qu'il y avait avant le Big Bang : ____.",
    "La pire idée de cadeau de dernière minute : ____.",
    "Ce qu'on devrait mettre sur les panneaux d'autoroute : ____.",
    "Le vrai programme spatial secret de la France : ____.",
    "Ce que les poules racontent entre elles : ____.",
    "La prochaine mise à jour d'iOS : ____.",
    "Le secret du bonheur selon un enfant de 5 ans : ____.",
];

const ANSWER_CARDS = [
    // --- Original ---
    "Un fromage qui pue",
    "La grève des transports",
    "Mon ex",
    "Les 35 heures",
    "Un apéro qui dure 3 jours",
    "La bise à un inconnu",
    "Un croissant rassis",
    "Le RSA",
    "Une raclette à 3h du matin",
    "Le droit de cuissage",
    "Un gilet jaune",
    "La Joconde qui sourit vraiment",
    "Un stage non rémunéré",
    "Le camembert nucléaire",
    "Un bébé qui juge",
    "Netflix et procrastination",
    "Le syndrome de la page blanche",
    "Une baguette comme arme",
    "Les impôts sur les impôts",
    "Une sieste existentielle",
    "Le Wi-Fi du voisin",
    "La queue à la Poste",
    "Un cours de philo à 8h",
    "La Sécu en faillite",
    "Un selfie avec le pape",
    "Les toilettes turques",
    "Un débat sur la chocolatine",
    "Le Père Noël au chômage",
    "Un karaoké de Johnny",
    "La triche au bac",
    "Les soldes chez Ikea",
    "Un match de pétanque truqué",
    "La fin du monde",
    "Un régime qui commence lundi",
    "Les pigeons de Paris",
    "Un pot de départ interminable",
    "Le permis de conduire à points",
    "Une manif qui tourne mal",
    "Le Tour de France dopé",
    "Un week-end chez belle-maman",
    "La file d'attente à Pôle Emploi",
    "Un mojito tiède",
    "Le syndrome de Stockholm",
    "Un PowerPoint de 200 slides",
    "La retraite à 95 ans",
    "Les moustiques en été",
    "Un tatouage raté",
    "Le lundi matin",
    "Un escape game avec sa famille",
    "La 5G dans le cerveau",
    "Un Jean-Pierre Foucault immortel",
    "Le complot des Illuminati",
    "Les Playmobil révolutionnaires",
    "Un barbecue végan",
    "Le code de la route",
    "Une lettre de motivation sincère",
    "Le mystère de la chaussette perdue",
    "Un enterrement de vie de garçon",
    "La météo de Brest",
    "Un steak haché surgelé",
    "Les abdos de Macron",
    "Le fantôme de De Gaulle",
    "Un match nul 0-0",
    "La flemme cosmique",
    "Un chat qui domine le monde",
    "Le sens de la vie (spoiler : 42)",
    "Une connexion Internet Explorer",
    "Un TGV en retard",
    "La calvitie précoce",
    "Un voyage scolaire en enfer",
    "Les soldes chez Lidl",
    "Le Nutella en rupture de stock",
    "Les Gaulois réfractaires",
    "Un algorithme de Tinder",
    "La crise de la quarantaine",
    "Un croissant au beurre de cacahuète",
    "La machine à café en panne",
    "Un week-end pluvieux en Normandie",
    "Le parking de Carrefour un samedi",
    "Une conspiration de chats",
    "Les cours de natation du président",
    "Un SMS envoyé à la mauvaise personne",
    "La police des mèmes",
    "Un dîner chez les Tuche",
    "L'odeur du métro en été",
    "Un robot qui fait la grève",
    "Le monde sans pain au chocolat",
    "Une réunion qui aurait pu être un email",
    "Un Kinder Surprise pour adultes",
    "Le retour des cassettes VHS",
    "Un brunch à 45 euros",
    "La philosophie de Jean-Claude Van Damme",
    "Un podcast sur la fiscalité",
    "Le comité des fêtes en colère",
    "Un influenceur à la retraite",
    "La privatisation de l'air",
    "Un escape game dans l'administration française",
    "Le dernier iPhone à 3000 euros",
    "Une garde à vue chez Mamie",
    "Le club des tricoteurs anonymes",
    "Un coach de vie en dépression",
    "La théorie du complot du gruyère",
    "Les ronds-points de province",
    "Un millionnaire au SMIC",
    "Le savoir-vivre à la française",
    "Une pizza hawaïenne devant un Italien",
    "Le recyclage des excuses",
    "Un chien influenceur",
    "La mondialisation du saucisson",
    "Un cours de yoga agressif",
    "La diplomatie du barbecue",
    "Un pot de Nutella vide",
    "Le 49.3 des sentiments",
    "Les pigeons espions du gouvernement",
    "Un apéro Teams",
    "La crise de nerfs au Monopoly",
    "Un road trip en Twingo",
    "Le droit à la paresse",
    "Une invasion de beaux-parents",
    "Le karma instantané",
    "Un festival de musique sous la pluie",
    "La révolution des post-it",
    "Un match de foot entre philosophes",
    "Le bonheur en CDD",
    "Une cure thermale à Tchernobyl",
    "Le complot des boulangeries",
    "Un stage de méditation avec Gérard Depardieu",

    // --- General (batch 2) ---
    "Un kebab à 2h du matin",
    "La procrastination olympique",
    "Un mariage à Vegas",
    "Les soldes chez Action",
    "Un coiffeur aveugle",
    "La recette secrète du pastis",
    "Un marathon de siestes",
    "Le complot des pharmaciens",
    "Un parapluie en feu",
    "La grève de la faim au McDo",
    "Un dentiste sadique",
    "Le retour du Minitel",
    "Un GPS qui ment",
    "La nostalgie du fax",
    "Un kangourou en liberté à Marseille",
    "Les doigts collants",
    "Un dimanche sans boulangerie",
    "Le Bluetooth qui ne se connecte jamais",
    "Un chat sur un Roomba",
    "La retraite spirituelle au Lidl",
    "Un médecin qui consulte WebMD",
    "Le stress du contrôle technique",
    "Un concert de Didier dans un garage",
    "La crise existentielle du hamster",
    "Un régime à base de fromage",
    "Le bruit du voisin du dessus à minuit",
    "Un pique-nique sous un pont",
    "La honte nationale",
    "Un clown triste",
    "Le contrôle fiscal surprise",
    "Un cours de cuisine raté en direct",
    "La malédiction du parapluie oublié",
    "Un thé à la menthe brûlant",
    "Le syndrome du dimanche soir",
    "Un anniversaire oublié",
    "La file d'attente chez le notaire",
    "Un ascenseur en panne entre deux étages",
    "Le mystère du bruit dans le grenier",
    "Un ice bucket challenge au pastis",
    "La sieste qui dure tout le week-end",
    "Un dîner aux chandelles chez Flunch",
    "Le complot des auto-écoles",
    "Un jogging en claquettes-chaussettes",
    "La grève des éboueurs en août",
    "Un speed dating au Pôle Emploi",
    "Le fantôme de la photocopieuse",
    "Un tour du monde en Clio",
    "La vengeance du facteur",
    "Un cours de danse avec un ours",
    "Le dernier carré de chocolat",
    "Un camping-car à Saint-Tropez",
    "La théorie du complot des chaussettes dépareillées",
    "Un braquage à la boulangerie",
    "Le scandale du Mont d'Or",
    "Un baptême de l'air en ULM",
    "La guerre des télécommandes",
    "Un apéro qui finit en garde à vue",
    "Le mystère du tupperware jamais rendu",
    "Un karaoké de Patrick Sébastien",
    "La honte post-soirée",
    "Un goûter d'anniversaire pour adultes",
    "Le régime Dukan version kebab",
    "Un taxi qui prend le périph à l'envers",
    "La fin des RTT",
    "Un stage de survie chez Ikea",
    "Le bouchon de la A7 en juillet",
    "Un mariage annulé au dernier moment",
    "La conspiration des boucheries halal-bio",
    "Un marathon Netflix de 72h",
    "Le dernier ticket de resto U",
    "Un séminaire sur la motivation le lundi",
    "La révolte des trottinettes électriques",
    "Un tatouage du prénom de son ex",
    "Le guide Michelin de la street food",
    "Un concert de triangle",
    "La crise de la brioche",
    "Un calendrier de l'Avent au saucisson",
    "Le syndrome de l'imposteur version française",
    "Un blind test de sonneries Nokia",
    "La révolte des stagiaires",

    // --- Dev & Tech ---
    "Un git push --force sur main un vendredi soir",
    "Le code legacy écrit par un stagiaire en 2009",
    "Un ticket Jira marqué 'Won't Fix'",
    "La dette technique de 14 ans",
    "Un déploiement en prod sans tests",
    "Le commit message 'fix stuff'",
    "Un daily standup de 45 minutes",
    "Stack Overflow qui tombe en panne",
    "Un if/else de 400 lignes",
    "Le mot de passe admin: admin123",
    "Un sprint de 6 semaines",
    "La migration qui devait prendre 2 jours",
    "Un merge conflict de 3000 lignes",
    "Le WiFi du coworking qui rame",
    "Un développeur full-stack qui ne connaît que HTML",
    "Le Dockerfile de 200 lignes",
    "Un Product Owner qui change d'avis tous les jours",
    "Le hotfix du hotfix du hotfix",
    "npm install qui casse tout",
    "Un code review de 47 fichiers un vendredi",
    "Le README qui dit 'TODO'",
    "Un bug qui n'existe qu'en prod",
    "La réunion d'architecture de 4 heures",
    "Le consultant qui copie-colle de ChatGPT",
    "Un certificat SSL expiré en pleine nuit",
    "Le 'ça marche sur ma machine'",
    "Un regex de 300 caractères",
    "Le Slack à 847 channels non lus",
    "Un dev qui code en Comic Sans",
    "La base de données sans index",
    "Un test unitaire qui teste rien",
    "Le backlog de 2000 tickets",
    "Un standup meeting assis",
    "Le fichier config.yml de 5000 lignes",
    "Un junior qui refactore tout le premier jour",
    "Le 'on refactorera plus tard'",
    "Un endpoint API avec 43 query params",
    "Le déploiement manuel du dimanche",
    "Un mot de passe en dur dans le code",
    "Le dashboard Grafana que personne ne regarde",
    "Un microservice qui fait tout",
    "Le 'c'est pas un bug, c'est une feature'",
    "Un sprint planning de 3 heures",
    "Le serveur de dev en feu",
    "Un variable nommée 'temp2_final_FINAL'",
    "La PR ouverte depuis 6 mois",
    "Un Scrum Master qui fait du waterfall",
    "Le fichier .env commité sur GitHub",
    "Un callback hell de 12 niveaux",
    "Le JSON de 4 Mo dans le localStorage",
    "Un CTO qui code encore en PHP 4",
    "Le kanban board avec 200 colonnes",
    "Un pipeline CI/CD de 45 minutes",
    "Le 'quick fix' qui prend 3 semaines",
    "Un dev qui refuse de toucher au CSS",
    "La doc Confluence de 2017",
    "Un debugger printf en production",
    "Le design pattern inventé à 3h du matin",
    "Un pair programming avec son manager",

    // --- Consulting ---
    "Un livrable de 300 slides pour dire 'oui'",
    "Le TJM à 1800€ pour faire des slides",
    "Un benchmark qui conclut ce que le client veut",
    "La matrice 2x2 qui résout tout",
    "Un consultant junior qui dit 'dans mon ancien cabinet'",
    "Le séminaire au ski facturé au client",
    "Un CODIR de 4h sans décision",
    "La transformation digitale qui transforme rien",
    "Un cabinet qui recrute ses propres anciens élèves",
    "Le McKinsey way appliqué au barbecue",
    "Un rapport d'audit de 600 pages jamais lu",
    "Le lean management appliqué à la cantine",
    "Un associé qui facture en dormant",
    "La synergy cross-functional du dernier quarter",
    "Un workshop post-it de 8 heures",
    "Le framework propriétaire vendu comme révolutionnaire",
    "Un junior qui dort au bureau pour impressionner",
    "La réorg annuelle qui change rien",
    "Un Uber Eats facturé en note de frais",
    "Le turnover de 40% présenté comme 'dynamisme'",
    "Un consultant qui dit 'il faut prendre du recul'",
    "La due diligence faite en 2 jours",
    "Un deck de 150 slides pour un call de 15 min",
    "Le business case inventé dans le taxi",
    "Un associé qui n'a pas codé depuis 1998",
    "La 'culture d'excellence' qui cache les heures sup",
    "Un KPI inventé pour justifier le budget",
    "Le consultant qui arrive avec sa propre matrice",
    "Un benchmark biaisé en faveur du client",
    "La lettre de mission incompréhensible",
    "Un manager qui staffé 5 projets en même temps",
    "Le knowledge management que personne n'utilise",
    "Un business plan sur un coin de nappe",
    "La formation obligatoire un samedi",
    "Un partner qui dit 'back in my days at BCG'",
    "Le projet 'stratégique' qui dure 18 mois",
    "Un Excel avec 47 onglets et aucune formule juste",
    "La facture de conseil plus chère que le projet",
    "Un RACI avec 200 lignes et aucun responsable",

    // --- General (batch 3) ---
    "Un crocodile dans les égouts de Paris",
    "La conspiration des boulangers bio",
    "Un cours de yoga pour chats",
    "Le fantôme du bureau 404",
    "Un régime paléo au McDo",
    "La grève des contrôleurs le jour de Noël",
    "Un karaoké forcé en team building",
    "Le retour de la disquette",
    "Un Uber Pool avec un mime",
    "La crise du beurre en Bretagne",
    "Un maître-nageur qui a peur de l'eau",
    "Le service après-vente de Wish",
    "Un anniversaire au bureau avec un gâteau Picard",
    "La théorie des cordes expliquée par un boulanger",
    "Un vol Ryanair debout",
    "Le brunch végan à 50 euros",
    "Un wedding planner pour divorces",
    "La disparition mystérieuse du papier toilette",
    "Un Airbnb hanté 5 étoiles",
    "Le dernier rond-point de France",
    "Un sommelier de bière",
    "La grève surprise des ascenseurs",
    "Un influenceur LinkedIn en manque de likes",
    "Le mystère du Ketchup sur le fromage",
    "Un Blablacar avec un ventriloque",
    "La retraite anticipée d'un chat",
    "Un escape game dans les bureaux de la CAF",
    "Le feng shui du HLM",
    "Un coaching en développement personnel par un chat",
    "La conspiration du gluten",
    "Un apéro dînatoire qui finit au Kebab",
    "Le mystère de la place de parking disparue",
    "Un bilan carbone négatif grâce au Pastis",
    "La théorie du chaos appliquée au ménage",
    "Un stage de survie dans les transports en commun",
    "Le guide spirituel du rond-point",
    "Un escape room dans les toilettes du bureau",
    "La crise d'identité du pain au chocolat",
    "Un documentaire Netflix sur les pigeons",
    "Le spa pour hamsters stressés",
    "Un mariage célébré par un robot",
    "La révolution des pantoufles connectées",
    "Un complot pour cacher les prises électriques",
    "Le dernier homme sur Terre qui rate son bus",
    "Un potager urbain sur un périphérique",
    "La réincarnation en rond-point",
    "Un concert de klaxons symphonique",
    "Le manifeste du lundi matin",
    "Un marathon de paperasse administrative",
    "La légende du Wifi gratuit qui marche",
];
